services:
  app:
    build: .
    container_name: pomodoro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--no-verbose", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
  nginx:
    image: nginx:alpine
    container_name: nginx_pomodoro
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      
volumes:
  logs:
    driver: local